name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Publish
        run: GOPROXY=proxy.golang.org go list -m github.com/janniclas/beehive@${{ github.ref_name }}
